-- Use the database
USE `project-db`;


-- All SFSU Major inserts
INSERT INTO Majors (MajorName) VALUES ('African-american studies');
INSERT INTO Majors (MajorName) VALUES ('Allied health');
INSERT INTO Majors (MajorName) VALUES ('American indian studies');
INSERT INTO Majors (MajorName) VALUES ('American studies');
INSERT INTO Majors (MajorName) VALUES ('Anthropology');
INSERT INTO Majors (MajorName) VALUES ('Apparel');
INSERT INTO Majors (MajorName) VALUES ('Applied mathematics');
INSERT INTO Majors (MajorName) VALUES ('Art history');
INSERT INTO Majors (MajorName) VALUES ('Art studies');
INSERT INTO Majors (MajorName) VALUES ('Asian-american studies');
INSERT INTO Majors (MajorName) VALUES ('Biochemistry');
INSERT INTO Majors (MajorName) VALUES ('Biological sciences');
INSERT INTO Majors (MajorName) VALUES ('Biology');
INSERT INTO Majors (MajorName) VALUES ('Black studies');
INSERT INTO Majors (MajorName) VALUES ('Business administration');
INSERT INTO Majors (MajorName) VALUES ('Business writing');
INSERT INTO Majors (MajorName) VALUES ('Chemistry');
INSERT INTO Majors (MajorName) VALUES ('Chicano studies');
INSERT INTO Majors (MajorName) VALUES ('Chinese language');
INSERT INTO Majors (MajorName) VALUES ('Cinema studies');
INSERT INTO Majors (MajorName) VALUES ('Civil engineering');
INSERT INTO Majors (MajorName) VALUES ('Classical languages');
INSERT INTO Majors (MajorName) VALUES ('Classical literatures');
INSERT INTO Majors (MajorName) VALUES ('Classics');
INSERT INTO Majors (MajorName) VALUES ('Communication sciences');
INSERT INTO Majors (MajorName) VALUES ('Comparative literature');
INSERT INTO Majors (MajorName) VALUES ('Computer engineering');
INSERT INTO Majors (MajorName) VALUES ('Computer science');
INSERT INTO Majors (MajorName) VALUES ('Conservation');
INSERT INTO Majors (MajorName) VALUES ('Consumer sciences');
INSERT INTO Majors (MajorName) VALUES ('Criminal justice');
INSERT INTO Majors (MajorName) VALUES ('Criticism');
INSERT INTO Majors (MajorName) VALUES ('Cultural minority studies');
INSERT INTO Majors (MajorName) VALUES ('Dance');
INSERT INTO Majors (MajorName) VALUES ('Design');
INSERT INTO Majors (MajorName) VALUES ('Disorders');
INSERT INTO Majors (MajorName) VALUES ('Drama');
INSERT INTO Majors (MajorName) VALUES ('Early childhood education');
INSERT INTO Majors (MajorName) VALUES ('Earth sciences');
INSERT INTO Majors (MajorName) VALUES ('Economics');
INSERT INTO Majors (MajorName) VALUES ('Education');
INSERT INTO Majors (MajorName) VALUES ('Electrical engineering');
INSERT INTO Majors (MajorName) VALUES ('Electronics engineering');
INSERT INTO Majors (MajorName) VALUES ('English language');
INSERT INTO Majors (MajorName) VALUES ('Environmental science');
INSERT INTO Majors (MajorName) VALUES ('Environmental studies');
INSERT INTO Majors (MajorName) VALUES ('Ethnic studies');
INSERT INTO Majors (MajorName) VALUES ('Family sciences');
INSERT INTO Majors (MajorName) VALUES ('Film studies');
INSERT INTO Majors (MajorName) VALUES ('Fitness');
INSERT INTO Majors (MajorName) VALUES ('French language');
INSERT INTO Majors (MajorName) VALUES ('Gender studies');
INSERT INTO Majors (MajorName) VALUES ('Geography');
INSERT INTO Majors (MajorName) VALUES ('Geological sciences');
INSERT INTO Majors (MajorName) VALUES ('Geosciences');
INSERT INTO Majors (MajorName) VALUES ('German language');
INSERT INTO Majors (MajorName) VALUES ('Government');
INSERT INTO Majors (MajorName) VALUES ('Group studies');
INSERT INTO Majors (MajorName) VALUES ('Health education');
INSERT INTO Majors (MajorName) VALUES ('Health sciences');
INSERT INTO Majors (MajorName) VALUES ('Health services');
INSERT INTO Majors (MajorName) VALUES ('Hispanic-american studies');
INSERT INTO Majors (MajorName) VALUES ('History');
INSERT INTO Majors (MajorName) VALUES ('Hospitality administration');
INSERT INTO Majors (MajorName) VALUES ('Humanities');
INSERT INTO Majors (MajorName) VALUES ('Humanistic studies');
INSERT INTO Majors (MajorName) VALUES ('Industrial arts teacher education');
INSERT INTO Majors (MajorName) VALUES ('Industrial design');
INSERT INTO Majors (MajorName) VALUES ('Interdisciplinary studies');
INSERT INTO Majors (MajorName) VALUES ('Interior design');
INSERT INTO Majors (MajorName) VALUES ('International relations');
INSERT INTO Majors (MajorName) VALUES ('Japanese language');
INSERT INTO Majors (MajorName) VALUES ('Jewish studies');
INSERT INTO Majors (MajorName) VALUES ('Journalism');
INSERT INTO Majors (MajorName) VALUES ('Labor studies');
INSERT INTO Majors (MajorName) VALUES ('Liberal arts');
INSERT INTO Majors (MajorName) VALUES ('Liberal studies');
INSERT INTO Majors (MajorName) VALUES ('Linguistics');
INSERT INTO Majors (MajorName) VALUES ('Literature');
INSERT INTO Majors (MajorName) VALUES ('Management');
INSERT INTO Majors (MajorName) VALUES ('Mathematics');
INSERT INTO Majors (MajorName) VALUES ('Mechanical engineering');
INSERT INTO Majors (MajorName) VALUES ('Mexican-american studies');
INSERT INTO Majors (MajorName) VALUES ('Multidisciplinary studies');
INSERT INTO Majors (MajorName) VALUES ('Music');
INSERT INTO Majors (MajorName) VALUES ('Music performance');
INSERT INTO Majors (MajorName) VALUES ('Native american studies');
INSERT INTO Majors (MajorName) VALUES ('Nutrition sciences');
INSERT INTO Majors (MajorName) VALUES ('Parks studies');
INSERT INTO Majors (MajorName) VALUES ('Philosophy');
INSERT INTO Majors (MajorName) VALUES ('Physical education');
INSERT INTO Majors (MajorName) VALUES ('Physics');
INSERT INTO Majors (MajorName) VALUES ('Political science');
INSERT INTO Majors (MajorName) VALUES ('Product design');
INSERT INTO Majors (MajorName) VALUES ('Professional writing');
INSERT INTO Majors (MajorName) VALUES ('Psychology');
INSERT INTO Majors (MajorName) VALUES ('Puerto rican studies');
INSERT INTO Majors (MajorName) VALUES ('Radio studies');
INSERT INTO Majors (MajorName) VALUES ('Recreation studies');
INSERT INTO Majors (MajorName) VALUES ('Registered nurse');
INSERT INTO Majors (MajorName) VALUES ('Registered nursing');
INSERT INTO Majors (MajorName) VALUES ('Religious studies');
INSERT INTO Majors (MajorName) VALUES ('Rhetoric');
INSERT INTO Majors (MajorName) VALUES ('Safety studies');
INSERT INTO Majors (MajorName) VALUES ('Scientific writing');
INSERT INTO Majors (MajorName) VALUES ('Social work');
INSERT INTO Majors (MajorName) VALUES ('Sociology');
INSERT INTO Majors (MajorName) VALUES ('Spanish language');
INSERT INTO Majors (MajorName) VALUES ('Speech communication');
INSERT INTO Majors (MajorName) VALUES ('Statistics');
INSERT INTO Majors (MajorName) VALUES ('Technology teacher education');
INSERT INTO Majors (MajorName) VALUES ('Television studies');
INSERT INTO Majors (MajorName) VALUES ('Textiles');
INSERT INTO Majors (MajorName) VALUES ('Theatre arts');
INSERT INTO Majors (MajorName) VALUES ('United states studies');
INSERT INTO Majors (MajorName) VALUES ('Urban studies');
INSERT INTO Majors (MajorName) VALUES ('Video studies');
INSERT INTO Majors (MajorName) VALUES ('Visual communications');


-- SFSU minor inserts
INSERT INTO Minors (MinorName) VALUES ('African Studies');
INSERT INTO Minors (MinorName) VALUES ('Africana Studies');
INSERT INTO Minors (MinorName) VALUES ('American Indian Studies');
INSERT INTO Minors (MinorName) VALUES ('American Studies');
INSERT INTO Minors (MinorName) VALUES ('Animation');
INSERT INTO Minors (MinorName) VALUES ('Anthropology');
INSERT INTO Minors (MinorName) VALUES ('Arab and Muslim Ethnicities and Diasporas Studies');
INSERT INTO Minors (MinorName) VALUES ('Art History');
INSERT INTO Minors (MinorName) VALUES ('Asian American Studies');
INSERT INTO Minors (MinorName) VALUES ('Astronomy');
INSERT INTO Minors (MinorName) VALUES ('Athletic Coaching');
INSERT INTO Minors (MinorName) VALUES ('Bilingual Spanish Journalism');
INSERT INTO Minors (MinorName) VALUES ('Biology, General');
INSERT INTO Minors (MinorName) VALUES ('Business Administration');
INSERT INTO Minors (MinorName) VALUES ('California Studies');
INSERT INTO Minors (MinorName) VALUES ('Chemistry');
INSERT INTO Minors (MinorName) VALUES ('Chinese Language');
INSERT INTO Minors (MinorName) VALUES ('Chinese Literature and Linguistics');
INSERT INTO Minors (MinorName) VALUES ('Cinema');
INSERT INTO Minors (MinorName) VALUES ('Civil Engineering');
INSERT INTO Minors (MinorName) VALUES ('Classics');
INSERT INTO Minors (MinorName) VALUES ('Comic Studies');
INSERT INTO Minors (MinorName) VALUES ('Communication Studies');
INSERT INTO Minors (MinorName) VALUES ('Comparative and World Literature');
INSERT INTO Minors (MinorName) VALUES ('Computer Engineering');
INSERT INTO Minors (MinorName) VALUES ('Computer Science');
INSERT INTO Minors (MinorName) VALUES ('Computing Applications');
INSERT INTO Minors (MinorName) VALUES ('Counseling');
INSERT INTO Minors (MinorName) VALUES ('Creative Writing');
INSERT INTO Minors (MinorName) VALUES ('Criminal Justice Studies');
INSERT INTO Minors (MinorName) VALUES ('Critical Mixed Race Studies');
INSERT INTO Minors (MinorName) VALUES ('Critical Pacific Islands & Oceania Studies');
INSERT INTO Minors (MinorName) VALUES ('Critical Social Thought');
INSERT INTO Minors (MinorName) VALUES ('Dance');
INSERT INTO Minors (MinorName) VALUES ('Decision Sciences');
INSERT INTO Minors (MinorName) VALUES ('Design');
INSERT INTO Minors (MinorName) VALUES ('Disability Studies');
INSERT INTO Minors (MinorName) VALUES ('Early Childhood Development');
INSERT INTO Minors (MinorName) VALUES ('Earth Sciences');
INSERT INTO Minors (MinorName) VALUES ('Economics');
INSERT INTO Minors (MinorName) VALUES ('Education');
INSERT INTO Minors (MinorName) VALUES ('Electrical Engineering');
INSERT INTO Minors (MinorName) VALUES ('Empowerment Self-Defense');
INSERT INTO Minors (MinorName) VALUES ('Entrepreneurship');
INSERT INTO Minors (MinorName) VALUES ('European Studies');
INSERT INTO Minors (MinorName) VALUES ('Feminist Health Justice');
INSERT INTO Minors (MinorName) VALUES ('Finance');
INSERT INTO Minors (MinorName) VALUES ('French');
INSERT INTO Minors (MinorName) VALUES ('Geography');
INSERT INTO Minors (MinorName) VALUES ('German');
INSERT INTO Minors (MinorName) VALUES ('Global Music and Dance');
INSERT INTO Minors (MinorName) VALUES ('Global Peace, Human Rights, and Justice Studies');
INSERT INTO Minors (MinorName) VALUES ('History');
INSERT INTO Minors (MinorName) VALUES ('Holistic Health');
INSERT INTO Minors (MinorName) VALUES ('Hospitality and Tourism Management');
INSERT INTO Minors (MinorName) VALUES ('Humanities');
INSERT INTO Minors (MinorName) VALUES ('Information Systems');
INSERT INTO Minors (MinorName) VALUES ('International Business');
INSERT INTO Minors (MinorName) VALUES ('International Relations');
INSERT INTO Minors (MinorName) VALUES ('Italian');
INSERT INTO Minors (MinorName) VALUES ('Japanese');
INSERT INTO Minors (MinorName) VALUES ('Jewish Studies');
INSERT INTO Minors (MinorName) VALUES ('Journalism');
INSERT INTO Minors (MinorName) VALUES ('Juvenile Justice');
INSERT INTO Minors (MinorName) VALUES ('Labor and Employment Studies');
INSERT INTO Minors (MinorName) VALUES ('Latin American Studies');
INSERT INTO Minors (MinorName) VALUES ('Latina/Latino Studies');
INSERT INTO Minors (MinorName) VALUES ('Linguistics');
INSERT INTO Minors (MinorName) VALUES ('Literature in English');
INSERT INTO Minors (MinorName) VALUES ('Management');
INSERT INTO Minors (MinorName) VALUES ('Marketing');
INSERT INTO Minors (MinorName) VALUES ('Mathematics');
INSERT INTO Minors (MinorName) VALUES ('Mechanical Engineering');
INSERT INTO Minors (MinorName) VALUES ('Media Literacy');
INSERT INTO Minors (MinorName) VALUES ('Middle East and Islamic Studies');
INSERT INTO Minors (MinorName) VALUES ('Modern Greek Studies');
INSERT INTO Minors (MinorName) VALUES ('Museum Studies');
INSERT INTO Minors (MinorName) VALUES ('Music');
INSERT INTO Minors (MinorName) VALUES ('Pacific Asian Studies');
INSERT INTO Minors (MinorName) VALUES ('Persian Studies');
INSERT INTO Minors (MinorName) VALUES ('Philosophy');
INSERT INTO Minors (MinorName) VALUES ('Philosophy and Religion');
INSERT INTO Minors (MinorName) VALUES ('Physics');
INSERT INTO Minors (MinorName) VALUES ('Political Science');
INSERT INTO Minors (MinorName) VALUES ('Psychology');
INSERT INTO Minors (MinorName) VALUES ('Prison Reentry Studies');
INSERT INTO Minors (MinorName) VALUES ('Professional Writing and Rhetoric');
INSERT INTO Minors (MinorName) VALUES ('Public Health');
INSERT INTO Minors (MinorName) VALUES ('Queer and Trans Studies');
INSERT INTO Minors (MinorName) VALUES ('Queer and Trans Ethnic Studies');
INSERT INTO Minors (MinorName) VALUES ('Race and Resistance Studies');
INSERT INTO Minors (MinorName) VALUES ('Recreation, Parks, and Tourism');
INSERT INTO Minors (MinorName) VALUES ('Religious Studies');
INSERT INTO Minors (MinorName) VALUES ('Russian');
INSERT INTO Minors (MinorName) VALUES ('Sociology');
INSERT INTO Minors (MinorName) VALUES ('South Asian Studies');
INSERT INTO Minors (MinorName) VALUES ('Sexuality Studies');
INSERT INTO Minors (MinorName) VALUES ('Spanish');
INSERT INTO Minors (MinorName) VALUES ('Special Education');
INSERT INTO Minors (MinorName) VALUES ('Studio Art');
INSERT INTO Minors (MinorName) VALUES ('Theatre Arts');
INSERT INTO Minors (MinorName) VALUES ('Urban Studies and Planning');
INSERT INTO Minors (MinorName) VALUES ('Video Game Studies');
INSERT INTO Minors (MinorName) VALUES ('Women and Gender Studies');
INSERT INTO Minors (MinorName) VALUES ('World Development Studies');