-- Use the database
USE `project-db`;


-- All SFSU Major inserts
INSERT INTO Minors (MinorName) VALUES ('Undeclared');
INSERT INTO Majors (MajorName) VALUES ('African-American Studies');
INSERT INTO Majors (MajorName) VALUES ('Allied Health');
INSERT INTO Majors (MajorName) VALUES ('American Indian Studies');
INSERT INTO Majors (MajorName) VALUES ('American Studies');
INSERT INTO Majors (MajorName) VALUES ('Anthropology');
INSERT INTO Majors (MajorName) VALUES ('Apparel');
INSERT INTO Majors (MajorName) VALUES ('Applied Mathematics');
INSERT INTO Majors (MajorName) VALUES ('Art History');
INSERT INTO Majors (MajorName) VALUES ('Art Studies');
INSERT INTO Majors (MajorName) VALUES ('Asian-American Studies');
INSERT INTO Majors (MajorName) VALUES ('Biochemistry');
INSERT INTO Majors (MajorName) VALUES ('Biological Sciences');
INSERT INTO Majors (MajorName) VALUES ('Biology');
INSERT INTO Majors (MajorName) VALUES ('Black Studies');
INSERT INTO Majors (MajorName) VALUES ('Business Administration');
INSERT INTO Majors (MajorName) VALUES ('Business Writing');
INSERT INTO Majors (MajorName) VALUES ('Chemistry');
INSERT INTO Majors (MajorName) VALUES ('Chicano Studies');
INSERT INTO Majors (MajorName) VALUES ('Chinese Language');
INSERT INTO Majors (MajorName) VALUES ('Cinema Studies');
INSERT INTO Majors (MajorName) VALUES ('Civil Engineering');
INSERT INTO Majors (MajorName) VALUES ('Classical Languages');
INSERT INTO Majors (MajorName) VALUES ('Classical Literatures');
INSERT INTO Majors (MajorName) VALUES ('Classics');
INSERT INTO Majors (MajorName) VALUES ('Communication Sciences');
INSERT INTO Majors (MajorName) VALUES ('Comparative Literature');
INSERT INTO Majors (MajorName) VALUES ('Computer Engineering');
INSERT INTO Majors (MajorName) VALUES ('Computer Science');
INSERT INTO Majors (MajorName) VALUES ('Conservation');
INSERT INTO Majors (MajorName) VALUES ('Consumer Sciences');
INSERT INTO Majors (MajorName) VALUES ('Criminal Justice');
INSERT INTO Majors (MajorName) VALUES ('Criticism');
INSERT INTO Majors (MajorName) VALUES ('Cultural Minority Studies');
INSERT INTO Majors (MajorName) VALUES ('Dance');
INSERT INTO Majors (MajorName) VALUES ('Design');
INSERT INTO Majors (MajorName) VALUES ('Disorders');
INSERT INTO Majors (MajorName) VALUES ('Drama');
INSERT INTO Majors (MajorName) VALUES ('Early Childhood Education');
INSERT INTO Majors (MajorName) VALUES ('Earth Sciences');
INSERT INTO Majors (MajorName) VALUES ('Economics');
INSERT INTO Majors (MajorName) VALUES ('Education');
INSERT INTO Majors (MajorName) VALUES ('Electrical Engineering');
INSERT INTO Majors (MajorName) VALUES ('Electronics Engineering');
INSERT INTO Majors (MajorName) VALUES ('English Language');
INSERT INTO Majors (MajorName) VALUES ('Environmental Science');
INSERT INTO Majors (MajorName) VALUES ('Environmental Studies');
INSERT INTO Majors (MajorName) VALUES ('Ethnic Studies');
INSERT INTO Majors (MajorName) VALUES ('Family Sciences');
INSERT INTO Majors (MajorName) VALUES ('Film Studies');
INSERT INTO Majors (MajorName) VALUES ('Fitness');
INSERT INTO Majors (MajorName) VALUES ('French Language');
INSERT INTO Majors (MajorName) VALUES ('Gender Studies');
INSERT INTO Majors (MajorName) VALUES ('Geography');
INSERT INTO Majors (MajorName) VALUES ('Geological Sciences');
INSERT INTO Majors (MajorName) VALUES ('Geosciences');
INSERT INTO Majors (MajorName) VALUES ('German Language');
INSERT INTO Majors (MajorName) VALUES ('Government');
INSERT INTO Majors (MajorName) VALUES ('Group Studies');
INSERT INTO Majors (MajorName) VALUES ('Health Education');
INSERT INTO Majors (MajorName) VALUES ('Health Sciences');
INSERT INTO Majors (MajorName) VALUES ('Health Services');
INSERT INTO Majors (MajorName) VALUES ('Hispanic-American Studies');
INSERT INTO Majors (MajorName) VALUES ('History');
INSERT INTO Majors (MajorName) VALUES ('Hospitality Administration');
INSERT INTO Majors (MajorName) VALUES ('Humanities');
INSERT INTO Majors (MajorName) VALUES ('Humanistic Studies');
INSERT INTO Majors (MajorName) VALUES ('Industrial Arts Teacher Education');
INSERT INTO Majors (MajorName) VALUES ('Industrial Design');
INSERT INTO Majors (MajorName) VALUES ('Interdisciplinary Studies');
INSERT INTO Majors (MajorName) VALUES ('Interior Design');
INSERT INTO Majors (MajorName) VALUES ('International Relations');
INSERT INTO Majors (MajorName) VALUES ('Japanese Language');
INSERT INTO Majors (MajorName) VALUES ('Jewish Studies');
INSERT INTO Majors (MajorName) VALUES ('Journalism');
INSERT INTO Majors (MajorName) VALUES ('Labor Studies');
INSERT INTO Majors (MajorName) VALUES ('Liberal Arts');
INSERT INTO Majors (MajorName) VALUES ('Liberal Studies');
INSERT INTO Majors (MajorName) VALUES ('Linguistics');
INSERT INTO Majors (MajorName) VALUES ('Literature');
INSERT INTO Majors (MajorName) VALUES ('Management');
INSERT INTO Majors (MajorName) VALUES ('Mathematics');
INSERT INTO Majors (MajorName) VALUES ('Mechanical Engineering');
INSERT INTO Majors (MajorName) VALUES ('Mexican-American Studies');
INSERT INTO Majors (MajorName) VALUES ('Multidisciplinary Studies');
INSERT INTO Majors (MajorName) VALUES ('Music');
INSERT INTO Majors (MajorName) VALUES ('Music Performance');
INSERT INTO Majors (MajorName) VALUES ('Native American Studies');
INSERT INTO Majors (MajorName) VALUES ('Nutrition Sciences');
INSERT INTO Majors (MajorName) VALUES ('Parks Studies');
INSERT INTO Majors (MajorName) VALUES ('Philosophy');
INSERT INTO Majors (MajorName) VALUES ('Physical Education');
INSERT INTO Majors (MajorName) VALUES ('Physics');
INSERT INTO Majors (MajorName) VALUES ('Political Science');
INSERT INTO Majors (MajorName) VALUES ('Product Design');
INSERT INTO Majors (MajorName) VALUES ('Professional Writing');
INSERT INTO Majors (MajorName) VALUES ('Psychology');
INSERT INTO Majors (MajorName) VALUES ('Puerto Rican Studies');
INSERT INTO Majors (MajorName) VALUES ('Radio Studies');
INSERT INTO Majors (MajorName) VALUES ('Recreation Studies');
INSERT INTO Majors (MajorName) VALUES ('Registered Nurse');
INSERT INTO Majors (MajorName) VALUES ('Registered Nursing');
INSERT INTO Majors (MajorName) VALUES ('Religious Studies');
INSERT INTO Majors (MajorName) VALUES ('Rhetoric');
INSERT INTO Majors (MajorName) VALUES ('Safety Studies');
INSERT INTO Majors (MajorName) VALUES ('Scientific Writing');
INSERT INTO Majors (MajorName) VALUES ('Social Work');
INSERT INTO Majors (MajorName) VALUES ('Sociology');
INSERT INTO Majors (MajorName) VALUES ('Spanish Language');
INSERT INTO Majors (MajorName) VALUES ('Speech Communication');
INSERT INTO Majors (MajorName) VALUES ('Statistics');
INSERT INTO Majors (MajorName) VALUES ('Technology Teacher Education');
INSERT INTO Majors (MajorName) VALUES ('Television Studies');
INSERT INTO Majors (MajorName) VALUES ('Textiles');
INSERT INTO Majors (MajorName) VALUES ('Theatre Arts');
INSERT INTO Majors (MajorName) VALUES ('United States Studies');
INSERT INTO Majors (MajorName) VALUES ('Urban Studies');
INSERT INTO Majors (MajorName) VALUES ('Video Studies');
INSERT INTO Majors (MajorName) VALUES ('Visual Communications');


-- SFSU minor inserts
INSERT INTO Minors (MinorName) VALUES ('N/A');
INSERT INTO Minors (MinorName) VALUES ('African Studies');
INSERT INTO Minors (MinorName) VALUES ('Africana Studies');
INSERT INTO Minors (MinorName) VALUES ('American Indian Studies');
INSERT INTO Minors (MinorName) VALUES ('American Studies');
INSERT INTO Minors (MinorName) VALUES ('Animation');
INSERT INTO Minors (MinorName) VALUES ('Anthropology');
INSERT INTO Minors (MinorName) VALUES ('Arab and Muslim Ethnicities and Diasporas Studies');
INSERT INTO Minors (MinorName) VALUES ('Art History');
INSERT INTO Minors (MinorName) VALUES ('Asian American Studies');
INSERT INTO Minors (MinorName) VALUES ('Astronomy');
INSERT INTO Minors (MinorName) VALUES ('Athletic Coaching');
INSERT INTO Minors (MinorName) VALUES ('Bilingual Spanish Journalism');
INSERT INTO Minors (MinorName) VALUES ('Biology, General');
INSERT INTO Minors (MinorName) VALUES ('Business Administration');
INSERT INTO Minors (MinorName) VALUES ('California Studies');
INSERT INTO Minors (MinorName) VALUES ('Chemistry');
INSERT INTO Minors (MinorName) VALUES ('Chinese Language');
INSERT INTO Minors (MinorName) VALUES ('Chinese Literature and Linguistics');
INSERT INTO Minors (MinorName) VALUES ('Cinema');
INSERT INTO Minors (MinorName) VALUES ('Civil Engineering');
INSERT INTO Minors (MinorName) VALUES ('Classics');
INSERT INTO Minors (MinorName) VALUES ('Comic Studies');
INSERT INTO Minors (MinorName) VALUES ('Communication Studies');
INSERT INTO Minors (MinorName) VALUES ('Comparative and World Literature');
INSERT INTO Minors (MinorName) VALUES ('Computer Engineering');
INSERT INTO Minors (MinorName) VALUES ('Computer Science');
INSERT INTO Minors (MinorName) VALUES ('Computing Applications');
INSERT INTO Minors (MinorName) VALUES ('Counseling');
INSERT INTO Minors (MinorName) VALUES ('Creative Writing');
INSERT INTO Minors (MinorName) VALUES ('Criminal Justice Studies');
INSERT INTO Minors (MinorName) VALUES ('Critical Mixed Race Studies');
INSERT INTO Minors (MinorName) VALUES ('Critical Pacific Islands & Oceania Studies');
INSERT INTO Minors (MinorName) VALUES ('Critical Social Thought');
INSERT INTO Minors (MinorName) VALUES ('Dance');
INSERT INTO Minors (MinorName) VALUES ('Decision Sciences');
INSERT INTO Minors (MinorName) VALUES ('Design');
INSERT INTO Minors (MinorName) VALUES ('Disability Studies');
INSERT INTO Minors (MinorName) VALUES ('Early Childhood Development');
INSERT INTO Minors (MinorName) VALUES ('Earth Sciences');
INSERT INTO Minors (MinorName) VALUES ('Economics');
INSERT INTO Minors (MinorName) VALUES ('Education');
INSERT INTO Minors (MinorName) VALUES ('Electrical Engineering');
INSERT INTO Minors (MinorName) VALUES ('Empowerment Self-Defense');
INSERT INTO Minors (MinorName) VALUES ('Entrepreneurship');
INSERT INTO Minors (MinorName) VALUES ('European Studies');
INSERT INTO Minors (MinorName) VALUES ('Feminist Health Justice');
INSERT INTO Minors (MinorName) VALUES ('Finance');
INSERT INTO Minors (MinorName) VALUES ('French');
INSERT INTO Minors (MinorName) VALUES ('Geography');
INSERT INTO Minors (MinorName) VALUES ('German');
INSERT INTO Minors (MinorName) VALUES ('Global Music and Dance');
INSERT INTO Minors (MinorName) VALUES ('Global Peace, Human Rights, and Justice Studies');
INSERT INTO Minors (MinorName) VALUES ('History');
INSERT INTO Minors (MinorName) VALUES ('Holistic Health');
INSERT INTO Minors (MinorName) VALUES ('Hospitality and Tourism Management');
INSERT INTO Minors (MinorName) VALUES ('Humanities');
INSERT INTO Minors (MinorName) VALUES ('Information Systems');
INSERT INTO Minors (MinorName) VALUES ('International Business');
INSERT INTO Minors (MinorName) VALUES ('International Relations');
INSERT INTO Minors (MinorName) VALUES ('Italian');
INSERT INTO Minors (MinorName) VALUES ('Japanese');
INSERT INTO Minors (MinorName) VALUES ('Jewish Studies');
INSERT INTO Minors (MinorName) VALUES ('Journalism');
INSERT INTO Minors (MinorName) VALUES ('Juvenile Justice');
INSERT INTO Minors (MinorName) VALUES ('Labor and Employment Studies');
INSERT INTO Minors (MinorName) VALUES ('Latin American Studies');
INSERT INTO Minors (MinorName) VALUES ('Latina/Latino Studies');
INSERT INTO Minors (MinorName) VALUES ('Linguistics');
INSERT INTO Minors (MinorName) VALUES ('Literature in English');
INSERT INTO Minors (MinorName) VALUES ('Management');
INSERT INTO Minors (MinorName) VALUES ('Marketing');
INSERT INTO Minors (MinorName) VALUES ('Mathematics');
INSERT INTO Minors (MinorName) VALUES ('Mechanical Engineering');
INSERT INTO Minors (MinorName) VALUES ('Media Literacy');
INSERT INTO Minors (MinorName) VALUES ('Middle East and Islamic Studies');
INSERT INTO Minors (MinorName) VALUES ('Modern Greek Studies');
INSERT INTO Minors (MinorName) VALUES ('Museum Studies');
INSERT INTO Minors (MinorName) VALUES ('Music');
INSERT INTO Minors (MinorName) VALUES ('Pacific Asian Studies');
INSERT INTO Minors (MinorName) VALUES ('Persian Studies');
INSERT INTO Minors (MinorName) VALUES ('Philosophy');
INSERT INTO Minors (MinorName) VALUES ('Philosophy and Religion');
INSERT INTO Minors (MinorName) VALUES ('Physics');
INSERT INTO Minors (MinorName) VALUES ('Political Science');
INSERT INTO Minors (MinorName) VALUES ('Psychology');
INSERT INTO Minors (MinorName) VALUES ('Prison Reentry Studies');
INSERT INTO Minors (MinorName) VALUES ('Professional Writing and Rhetoric');
INSERT INTO Minors (MinorName) VALUES ('Public Health');
INSERT INTO Minors (MinorName) VALUES ('Queer and Trans Studies');
INSERT INTO Minors (MinorName) VALUES ('Queer and Trans Ethnic Studies');
INSERT INTO Minors (MinorName) VALUES ('Race and Resistance Studies');
INSERT INTO Minors (MinorName) VALUES ('Recreation, Parks, and Tourism');
INSERT INTO Minors (MinorName) VALUES ('Religious Studies');
INSERT INTO Minors (MinorName) VALUES ('Russian');
INSERT INTO Minors (MinorName) VALUES ('Sociology');
INSERT INTO Minors (MinorName) VALUES ('South Asian Studies');
INSERT INTO Minors (MinorName) VALUES ('Sexuality Studies');
INSERT INTO Minors (MinorName) VALUES ('Spanish');
INSERT INTO Minors (MinorName) VALUES ('Special Education');
INSERT INTO Minors (MinorName) VALUES ('Studio Art');
INSERT INTO Minors (MinorName) VALUES ('Theatre Arts');
INSERT INTO Minors (MinorName) VALUES ('Urban Studies and Planning');
INSERT INTO Minors (MinorName) VALUES ('Video Game Studies');
INSERT INTO Minors (MinorName) VALUES ('Women and Gender Studies');
INSERT INTO Minors (MinorName) VALUES ('World Development Studies');



