USE `project-db`;

CREATE TABLE IF NOT EXISTS Hashtags (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Tag VARCHAR(100) NOT NULL UNIQUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PostHashtags (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    HashtagID INT NOT NULL,
    FOREIGN KEY (PostID) REFERENCES Posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (HashtagID) REFERENCES Hashtags(ID) ON DELETE CASCADE,
    UNIQUE (PostID, HashtagID)
);